In [ ]:
import pandas as pd
import numpy as np

# **Importing Csv files**

In [ ]:
oms=pd.read_csv('oms.csv')
pf=pd.read_csv('pf.csv')

In [ ]:
oms.head()

,Unnamed: 0,awbno,getStatus,inventory_status,orderID,subOrder,date,received_date,SKU,return_courier,warehouse,returnType,shelf_code,return_status,putaway_code,putaway_status
0,0,R1010808154AJI,GOOD_INVENTORY,COMPLETE,5076519403,1011866143.5-1,01/11/24 00:44,08/11/24 15:05,8905723077969,SELF,NaN,return,R05-05-4H,COMPLETE,PT8478,COMPLETE
1,1,5979920051,GOOD_INVENTORY,COMPLETE,2865,1.41502E+13,01/11/24 12:13,09/11/24 13:47,8905723168452,ECOM_1,NaN,return,R05-09-3B,COMPLETE,PT8517,COMPLETE
2,2,627721482658,GOOD_INVENTORY,NaN,406-3863912-5131562,406-3863912-5131562-1,01/11/24 12:21,11/11/24 20:36,8905723129194,ATSIN,NaN,return,R06-05-1A,COURIER_ALLOCATED,NaN,NaN
3,3,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-0,01/11/24 12:44,08/11/24 18:10,8905723296971,SELF,NaN,return,R05-05-4H,COMPLETE,PT8491,COMPLETE
4,4,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-1,01/11/24 12:44,08/11/24 18:10,8905723297077,SELF,NaN,return,R05-05-4H,COMPLETE,PT8491,COMPLETE

In [ ]:
pf.head()

,Unnamed: 0,awbno,Return status,Return Quantity,Reason,SKU,orderID,date,platform,SKU_child
0,0,R972189457AJI,RETURN_PROCESSED,1,Does_Not_Fit_Well,8905723134259,S262541859,30/09/24 23:28,Channel 1,8905723134259
1,1,195042149034376,RETURN_PROCESSED,1,Not_Happy_With_Product_Quality,8905723297022,S262409205,30/09/24 21:59,Channel 1,8905723297022
2,2,195042149034376,RETURN_PROCESSED,1,Not_Happy_With_Product_Quality,8905723143558,S262409205,30/09/24 21:59,Channel 1,8905723143558
3,3,R960845268AJI,RETURN_PROCESSED,1,Want_To_Change_Style_Color,8905723309114,S262949936,30/09/24 21:58,Channel 1,8905723309114
4,4,R966944831AJI,RETURN_PROCESSED,1,Does_Not_Look_Good_On_Me,8905723143589,S262726902,30/09/24 21:56,Channel 1,8905723143589

In [ ]:
oms.shape

(25173, 16)

In [ ]:
pf.shape

(28154, 10)

In [ ]:
oms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25173 entries, 0 to 25172
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        25173 non-null  int64
 1   awbno             23061 non-null  object
 2   getStatus         24643 non-null  object
 3   inventory_status  22730 non-null  object
 4   orderID           25173 non-null  object
 5   subOrder          25173 non-null  object
 6   date              25173 non-null  object
 7   received_date     18479 non-null  object
 8   SKU               25173 non-null  int64
 9   return_courier    23061 non-null  object
 10  warehouse         0 non-null      float64
 11  returnType        25173 non-null  object
 12  shelf_code        25067 non-null  object
 13  return_status     25173 non-null  object
 14  putaway_code      22200 non-null  object
 15  putaway_status    16261 non-null  object
dtypes: float64(1), int64(2), object(13)
memory usage: 3.1+ MB

In [ ]:
pf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28154 entries, 0 to 28153
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       28154 non-null  int64
 1   awbno            27752 non-null  object
 2   Return status    27563 non-null  object
 3   Return Quantity  28154 non-null  int64
 4   Reason           21413 non-null  object
 5   SKU              28154 non-null  object
 6   orderID          27993 non-null  object
 7   date             28154 non-null  object
 8   platform         28154 non-null  object
 9   SKU_child        28154 non-null  object
dtypes: int64(2), object(8)
memory usage: 2.1+ MB

Converting awbno and SKU to string

In [ ]:
oms['SKU']=oms['SKU'].astype("string")
oms['awbno']=oms['awbno'].astype("string")
pf['SKU']=pf['SKU'].astype("string")
pf['awbno']=pf['awbno'].astype("string")

In [ ]:
oms['SKU']=oms['SKU'].str.strip()
oms['awbno']=oms['awbno'].str.strip()
pf['SKU']=pf['SKU'].str.strip()
pf['awbno']=pf['awbno'].str.strip()

In [ ]:
print(oms.dtypes['awbno'])
print(oms.dtypes['SKU'])
print(pf.dtypes['awbno'])
print(pf.dtypes['SKU'])

string
string
string
string

Dropping "Unnamed: 0" column

In [ ]:
oms.drop('Unnamed: 0',axis=1,inplace=True)
pf.drop('Unnamed: 0',axis=1,inplace=True)

Dropping Duplicates from oms and pf

In [ ]:
oms.drop_duplicates(inplace=True)
pf.drop_duplicates(inplace=True)

In [ ]:
oms.shape

(24028, 15)

In [ ]:
pf.shape

(28154, 9)

Merging sku and awbno for both datasets

In [ ]:
oms['SK_aws']=oms['SKU']+"-"+oms['awbno']
pf['SK_aws']=pf['SKU']+"-"+pf['awbno']

In [ ]:
oms.head()

,awbno,getStatus,inventory_status,orderID,subOrder,date,received_date,SKU,return_courier,warehouse,returnType,shelf_code,return_status,putaway_code,putaway_status,SK_aws
0,R1010808154AJI,GOOD_INVENTORY,COMPLETE,5076519403,1011866143.5-1,01/11/24 00:44,08/11/24 15:05,8905723077969,SELF,NaN,return,R05-05-4H,COMPLETE,PT8478,COMPLETE,8905723077969-R1010808154AJI
1,5979920051,GOOD_INVENTORY,COMPLETE,2865,1.41502E+13,01/11/24 12:13,09/11/24 13:47,8905723168452,ECOM_1,NaN,return,R05-09-3B,COMPLETE,PT8517,COMPLETE,8905723168452-5979920051
2,627721482658,GOOD_INVENTORY,NaN,406-3863912-5131562,406-3863912-5131562-1,01/11/24 12:21,11/11/24 20:36,8905723129194,ATSIN,NaN,return,R06-05-1A,COURIER_ALLOCATED,NaN,NaN,8905723129194-627721482658
3,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-0,01/11/24 12:44,08/11/24 18:10,8905723296971,SELF,NaN,return,R05-05-4H,COMPLETE,PT8491,COMPLETE,8905723296971-195042167901922
4,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-1,01/11/24 12:44,08/11/24 18:10,8905723297077,SELF,NaN,return,R05-05-4H,COMPLETE,PT8491,COMPLETE,8905723297077-195042167901922

In [ ]:
oms.isna().sum()
pf.isna().sum()

awbno               402
Return status       591
Return Quantity       0
Reason             6741
SKU                   0
orderID             161
date                  0
platform              0
SKU_child             0
SK_aws              402
dtype: int64

In [ ]:
pf.head()

,awbno,Return status,Return Quantity,Reason,SKU,orderID,date,platform,SKU_child,SK_aws
0,R972189457AJI,RETURN_PROCESSED,1,Does_Not_Fit_Well,8905723134259,S262541859,30/09/24 23:28,Channel 1,8905723134259,8905723134259-R972189457AJI
1,195042149034376,RETURN_PROCESSED,1,Not_Happy_With_Product_Quality,8905723297022,S262409205,30/09/24 21:59,Channel 1,8905723297022,8905723297022-195042149034376
2,195042149034376,RETURN_PROCESSED,1,Not_Happy_With_Product_Quality,8905723143558,S262409205,30/09/24 21:59,Channel 1,8905723143558,8905723143558-195042149034376
3,R960845268AJI,RETURN_PROCESSED,1,Want_To_Change_Style_Color,8905723309114,S262949936,30/09/24 21:58,Channel 1,8905723309114,8905723309114-R960845268AJI
4,R966944831AJI,RETURN_PROCESSED,1,Does_Not_Look_Good_On_Me,8905723143589,S262726902,30/09/24 21:56,Channel 1,8905723143589,8905723143589-R966944831AJI

Merging oms and pf

In [ ]:
mg_df=oms.merge(pf,on='SK_aws',how='left',suffixes=('_oms','_pf'))

In [ ]:
mg_df.head()

,awbno_oms,getStatus,inventory_status,orderID_oms,subOrder,date_oms,received_date,SKU_oms,return_courier,warehouse,...,SK_aws,awbno_pf,Return status,Return Quantity,Reason,SKU_pf,orderID_pf,date_pf,platform,SKU_child
0,R1010808154AJI,GOOD_INVENTORY,COMPLETE,5076519403,1011866143.5-1,01/11/24 00:44,08/11/24 15:05,8905723077969,SELF,NaN,...,8905723077969-R1010808154AJI,R1010808154AJI,RETURN_CREATED,1.0,Not_Happy_With_Product_Quality,8905723077969,1011866143,31/10/24 23:48,Channel 1,8905723077969
1,5979920051,GOOD_INVENTORY,COMPLETE,2865,1.41502E+13,01/11/24 12:13,09/11/24 13:47,8905723168452,ECOM_1,NaN,...,8905723168452-5979920051,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
2,627721482658,GOOD_INVENTORY,NaN,406-3863912-5131562,406-3863912-5131562-1,01/11/24 12:21,11/11/24 20:36,8905723129194,ATSIN,NaN,...,8905723129194-627721482658,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
3,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-0,01/11/24 12:44,08/11/24 18:10,8905723296971,SELF,NaN,...,8905723296971-195042167901922,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN
4,195042167901922,GOOD_INVENTORY,COMPLETE,5076181331,S266159169.1-1-1,01/11/24 12:44,08/11/24 18:10,8905723297077,SELF,NaN,...,8905723297077-195042167901922,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN

In [ ]:
mg_df.shape

(846396, 25)

In [ ]:
mg_df.isna().sum()

awbno_oms           823698
getStatus              593
inventory_status     56869
orderID_oms              0
subOrder                 0
date_oms                 0
received_date         6608
SKU_oms                  0
return_courier      823698
warehouse           846396
returnType               0
shelf_code            8520
return_status            0
putaway_code         57462
putaway_status       63267
SK_aws              823698
awbno_pf            832033
Return status       391708
Return Quantity       8335
Reason              101608
SKU_pf                8335
orderID_pf          272656
date_pf               8335
platform              8335
SKU_child             8335
dtype: int64

Replacing Null values with Blank

In [ ]:
mg_df['awbno_pf']=mg_df['awbno_pf'].fillna('')
mg_df['awbno_oms']=mg_df['awbno_oms'].fillna('')
mg_df['SKU_pf']=mg_df['SKU_pf'].fillna('')
mg_df['inventory_status']=mg_df['inventory_status'].fillna('')
mg_df['getStatus']=mg_df['getStatus'].fillna('')

In [ ]:
mg_df.isna().sum()

awbno_oms           823698
getStatus                0
inventory_status         0
orderID_oms              0
subOrder                 0
date_oms                 0
received_date         6608
SKU_oms                  0
return_courier      823698
warehouse           846396
returnType               0
shelf_code            8520
return_status            0
putaway_code         57462
putaway_status       63267
SK_aws              823698
awbno_pf                 0
Return status       391708
Return Quantity       8335
Reason              101608
SKU_pf                   0
orderID_pf          272656
date_pf               8335
platform              8335
SKU_child             8335
dtype: int64

Logic for "final_inventory_status"

In [ ]:
def get_inventory_status(row):
    # Check if both awbno and sku match
    if row['awbno_oms'] == row['awbno_pf'] and row['SKU_oms'] == row['SKU_pf'] :
        return row['getStatus']
    elif row['awbno_oms'] == row['awbno_pf']:
                return str(row['getStatus']) + "_sku-mismatch"
    else:
                return "missing"
mg_df['final_inventory_status'] = mg_df.apply(get_inventory_status, axis=1)

# Display the result

Converting Merged Data into a CSV file

In [ ]:
mg_df.to_csv('final_df.csv')